### ISSUE TITLE
[ENHANCEMENT] Add a few commands

### ISSUE THREAD

**Issue by SuperMeepEnby** [SuperMeepBoy/wikitransbot#27]
@wikitransbot intro -> sur wikitrans.co/intro
@wikitransbot trombinoscope / trombi / galerie -> wikitrans.co/modeles
@wikitransbot carte -> wikitrans.co/carte/
@wikitransbot aide / help -> must explain all the commands

**Comment by SuperMeepEnby** [comment]
Without diving into the details it might be a good idea to look at the configuration file move everything related to commands in a "commands" section.

**Comment by MoiTux** [comment]
` @wikitransbot aide / help -> must explain all the commands`  
I thing this won't be possible due to the limitation of char in a tweet   
but it could redirect into the Readme here or a specific page on wiktrans (but i don't thinks this is a good idea) to explain how to use it.

**Comment by SuperMeepEnby** [comment]
@MoiTux Yes, I had that in mind too. I asked the Wikitrans team what solution they prefer. Below is the conclusion.

For the help command it has been decided with the Wikitrans team that the answer would be a redirection to the README.md, in a "Usage" section.
A script will be created to generate that section automatically in order to ensure every single new command that is added to the bot is reflected in the README.md.

**Comment by SuperMeepEnby** [comment]
Done in #32
